import { API_PATH, SERVER } from "../constant.js";

function showPre(id, data) {
    const el = document.getElementById(id);
    if (!el) return;
    el.textContent = typeof data === "string" ? data : JSON.stringify(data, null, 2);
    el.classList.remove("hidden");
}

async function loadHealth() {
    const pre = document.getElementById("opsHealthJson");
    try {
        const res = await axios.get(SERVER + API_PATH.HEALTH_DASHBOARD_PATH);
        if (pre) pre.textContent = JSON.stringify(res.data, null, 2);
    } catch (err) {
        if (pre) pre.textContent = err.message || "Failed to load health";
    }
}

async function loadFolders() {
    const sel = document.getElementById("opsFolderSelect");
    if (!sel) return;
    try {
        const res = await axios.get(SERVER + API_PATH.SCAN_FOLDERS_PATH);
        const folders = res.data?.folders || [];
        sel.innerHTML = '<option value="">— Select folder —</option>';
        for (const f of folders) {
            const opt = document.createElement("option");
            opt.value = f.name;
            opt.textContent = `${f.name} (~${f.pcap_count_hint} pcap)`;
            sel.appendChild(opt);
        }
    } catch (_) {
        /* ignore */
    }
}

function downloadText(filename, content, mime) {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
}

function buildWiresharkBat(paths) {
    const lines = ["@echo off", "REM Generated by PCAP Ops"];
    for (const p of paths) {
        const escaped = p.replace(/"/g, '""');
        lines.push(`start "" wireshark "${escaped}"`);
    }
    return lines.join("\r\n");
}

function buildWiresharkSh(paths) {
    const lines = ["#!/bin/sh", "# Generated by PCAP Ops"];
    for (const p of paths) {
        const escaped = p.replace(/"/g, '\\"');
        lines.push(`wireshark "${escaped}" &`);
    }
    return lines.join("\n");
}

document.getElementById("opsRefreshBtn")?.addEventListener("click", () => {
    loadHealth();
    loadFolders();
});

document.getElementById("opsDuplicatesBtn")?.addEventListener("click", async () => {
    try {
        const res = await axios.get(SERVER + API_PATH.CATALOG_DUPLICATES_PATH, {
            params: { max_groups: 30 }
        });
        showPre("opsDuplicatesOut", res.data);
    } catch (err) {
        showPre("opsDuplicatesOut", err.response?.data || err.message);
    }
});

document.getElementById("opsOrphansBtn")?.addEventListener("click", async () => {
    try {
        const res = await axios.get(SERVER + API_PATH.CATALOG_ORPHANS_PATH);
        showPre("opsOrphansOut", res.data);
    } catch (err) {
        showPre("opsOrphansOut", err.response?.data || err.message);
    }
});

document.getElementById("opsNewIpsBtn")?.addEventListener("click", async () => {
    try {
        const res = await axios.get(SERVER + API_PATH.CATALOG_NEW_IPS_PATH);
        showPre("opsNewIpsOut", res.data);
    } catch (err) {
        showPre("opsNewIpsOut", err.response?.data || err.message);
    }
});

document.getElementById("opsResetIpsBtn")?.addEventListener("click", async () => {
    try {
        const res = await axios.post(SERVER + API_PATH.CATALOG_IPS_RESET_PATH);
        showPre("opsNewIpsOut", res.data);
    } catch (err) {
        showPre("opsNewIpsOut", err.response?.data || err.message);
    }
});

document.getElementById("opsSnapshotIpsBtn")?.addEventListener("click", async () => {
    try {
        const res = await axios.post(SERVER + API_PATH.CATALOG_IPS_SNAPSHOT_PATH);
        showPre("opsNewIpsOut", res.data);
    } catch (err) {
        showPre("opsNewIpsOut", err.response?.data || err.message);
    }
});

document.getElementById("opsMergeBtn")?.addEventListener("click", async () => {
    const status = document.getElementById("opsMergeStatus");
    const raw = document.getElementById("opsMergeHashes")?.value || "";
    const hashes = raw
        .split(/[\s,]+/)
        .map((h) => h.trim())
        .filter(Boolean);
    if (hashes.length < 2) {
        if (status) status.textContent = "At least 2 hashes required.";
        return;
    }
    if (status) status.textContent = "Merging…";
    try {
        const res = await axios.post(
            SERVER + API_PATH.PCAP_MERGE_PATH,
            { file_hashes: hashes },
            { responseType: "blob" }
        );
        const url = URL.createObjectURL(res.data);
        const a = document.createElement("a");
        a.href = url;
        a.download = "merged.pcap";
        a.click();
        URL.revokeObjectURL(url);
        if (status) status.textContent = "Downloaded merged.pcap";
    } catch (err) {
        if (status) status.textContent = err.response?.data?.detail || err.message || "Merge failed";
    }
});

document.getElementById("opsFolderScanBtn")?.addEventListener("click", async () => {
    const status = document.getElementById("opsFolderStatus");
    const folder = document.getElementById("opsFolderSelect")?.value?.trim();
    if (!folder) {
        if (status) status.textContent = "Select a folder first.";
        return;
    }
    if (status) status.textContent = "Starting scan…";
    try {
        const res = await axios.post(SERVER + API_PATH.REINDEX_FOLDER_PATH, { folder });
        if (status) status.textContent = JSON.stringify(res.data);
    } catch (err) {
        if (status) status.textContent = err.response?.data?.message || err.message;
    }
});

document.getElementById("opsWireBatBtn")?.addEventListener("click", () => {
    const paths = (document.getElementById("opsWirePaths")?.value || "")
        .split("\n")
        .map((p) => p.trim())
        .filter(Boolean);
    if (!paths.length) return;
    downloadText("open-wireshark.bat", buildWiresharkBat(paths), "text/plain");
});

document.getElementById("opsWireShBtn")?.addEventListener("click", () => {
    const paths = (document.getElementById("opsWirePaths")?.value || "")
        .split("\n")
        .map((p) => p.trim())
        .filter(Boolean);
    if (!paths.length) return;
    downloadText("open-wireshark.sh", buildWiresharkSh(paths), "text/plain");
});

loadHealth();
loadFolders();
